from db_connection import get_connection # <--- Usamos tu sistema de seguridad centralizado

def create_habits_table():
    conn = None
    try:
        # Obtenemos la conexión sin exponer tus claves secretas
        conn = get_connection()
        if conn is None:
            return
            
        cursor = conn.cursor()
        
        # SQL para crear la tabla de hábitos diarios
        sql = """
        CREATE TABLE daily_habits (
            habit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            habit_name VARCHAR2(100),
            status VARCHAR2(20),
            category VARCHAR2(50),
            log_date DATE DEFAULT SYSDATE
        )
        """
        
        cursor.execute(sql)
        print("✅ Tabla 'daily_habits' creada. ¡Tus rachas empiezan hoy! 🇦🇺")
        
    except Exception as e:
        # Manejo elegante si la tabla ya existe (Error ORA-00955 en Oracle)
        if "ORA-00955" in str(e):
            print("ℹ️ La tabla 'daily_habits' ya existe. No es necesario crearla de nuevo.")
        else:
            print(f"❌ Error inesperado: {e}")
    finally:
        if conn:
            conn.close()

if __name__ == "__main__":
    create_habits_table()