from db_connection import get_connection # <--- Tu conexión centralizada y segura

def setup_gym_table():
    conn = None
    try:
        # Obtenemos la conexión sin exponer contraseñas
        conn = get_connection()
        if conn is None:
            return
            
        cursor = conn.cursor()
        
        # Tabla Normalizada para el Gym
        sql = """
        CREATE TABLE gym_progress (
            workout_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            exercise_name VARCHAR2(100),
            weight_kg NUMBER(6,2),
            reps NUMBER,
            workout_date DATE DEFAULT SYSDATE,
            workout_day VARCHAR2(20),
            sets NUMBER
        )
        """
        # Nota: He añadido 'workout_day' y 'sets' para que coincida 
        # con tus scripts de registro granular y PPL.
        
        cursor.execute(sql)
        print("✅ Tabla 'gym_progress' creada con éxito. ¡Todo listo para los Gains! 💪")
        
    except Exception as e:
        # Manejo específico si la tabla ya existe
        if "ORA-00955" in str(e):
            print("ℹ️ La tabla 'gym_progress' ya existe en tu base de datos.")
        else:
            print(f"❌ Error inesperado: {e}")
    finally:
        if conn:
            conn.close()

if __name__ == "__main__":
    setup_gym_table()