from db_connection import get_connection # <--- Usamos el sistema de secretos

def create_money_table():
    conn = None
    try:
        # Obtenemos la conexión segura
        conn = get_connection()
        if conn is None:
            return
            
        cursor = conn.cursor()
        
        # SQL para crear la tabla de ahorros
        sql = """
        CREATE TABLE australia_fund (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            entry_date DATE DEFAULT SYSDATE,
            amount NUMBER(10,2),
            description VARCHAR2(100)
        )
        """
        
        cursor.execute(sql)
        print("✅ ¡Tabla 'australia_fund' creada con éxito! Ya tienes dónde guardar tus dólares para el viaje. 🇦🇺")
        
    except Exception as e:
        # Si la tabla ya existe, Oracle lanzará un error. Lo manejamos aquí:
        if "ORA-00955" in str(e):
            print("ℹ️ La tabla 'australia_fund' ya existe. No es necesario crearla de nuevo.")
        else:
            print(f"❌ Error al crear la tabla: {e}")
    finally:
        if conn:
            conn.close()

if __name__ == "__main__":
    create_money_table()